# WARNING: this is only for testing purposes. Do not install in a production
# cluster.
#
# This exposes the hostpath's Unix domain csi.sock as a TCP port to the
# outside world. The mapping from Unix domain socket to TCP is done
# by socat.
#
# This is useful for testing with csi-sanity or csc.

apiVersion: v1
kind: Service
metadata:
  name: hostpath-service
spec:
  type: NodePort
  selector:
    app: csi-hostpath-socat
  ports:
  - port: 10000 # fixed port inside the pod, dynamically allocated port outside
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-hostpath-socat
spec:
  serviceName: "csi-hostpath-socat"
  replicas: 1
  selector:
    matchLabels:
      app: csi-hostpath-socat
  template:
    metadata:
      labels:
        app: csi-hostpath-socat
    spec:
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
        - name: socat
          image: {{ .Values.testing.repository }}:{{ .Values.testing.tag }}
          imagePullPolicy: {{ .Values.testing.pullPolicy }}
          args:
            - tcp-listen:10000,fork,reuseaddr
            - unix-connect:/csi/csi.sock
          securityContext:
            # This is necessary only for systems with SELinux, where
            # non-privileged sidecar containers cannot access unix domain socket
            # created by privileged CSI driver container.
            privileged: true
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/{{ .Values.driver.name }}
            type: DirectoryOrCreate
          name: socket-dir
