kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-hostpath-resizer
spec:
  serviceName: "csi-hostpath-resizer"
  replicas: 1
  selector:
    matchLabels:
      app: csi-hostpath-resizer
  template:
    metadata:
      labels:
        app: csi-hostpath-resizer
    spec:
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
      serviceAccountName: csi-resizer
      containers:
        - name: csi-resizer
          image: {{ .Values.resizer.repository }}:{{ .Values.resizer.tag }}
          imagePullPolicy: {{ .Values.resizer.pullPolicy }}
          args:
            - -v=5
            - -csi-address=/csi/csi.sock
          securityContext:
            # This is necessary only for systems with SELinux, where
            # non-privileged sidecar containers cannot access unix domain socket
            # created by privileged CSI driver container.
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/{{ .Values.driver.name }}
            type: DirectoryOrCreate
          name: socket-dir
